### ISSUE TITLE
Design and add support for NUnit engine extensions

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-engine#199]
Although we recognize NUnit extension attributes and will try to load them if they are present, loading of existing extensions does not succeed in most cases. The reasons for this vary from one extension to another, so each extension needs to be addressed separately. In general, the problem is that the existing extensions implement NUnit interfaces whereas TestCentric is expecting a TC interface of the same name. In addition, some extension methods return objects defined within NUnit, which we do not support.

We could solve these problems easily by importing and directly using the NUnit types but this would only be useful for extension points for which we do not expect to have TC-specific extensions. If we intend to have both NUnit and TC extensions for a given extension point, then some way for the two to co-exist must be developed.

Some extensions may be developed by third-parties, including NUnit users. Since we will usually be unaware of such extensions, they are not included in the scope of this issue, with the exception of ITestEventListener. We know that has been implemented by many users and will need to be completely supported for that reason

The scope of this issue includes the following ExtensionPoints, which exist in NUnit and are duplicated in TestCentric:

- [ ] IDriverFactory (Existing extension: nunit-v2-framework-driver)
- [ ] IProjectLoader (Existing extensions: nunit-project-loader and vs-project-loader)
- [x] IResultWriter (Existing extension: nunit-v2-result-writer)
- [ ] IService (No existing extensions)
- [x] ITestEventListener (Existing extension: teamcity-event-listener)

**Comment by CharliePoole** [comment]
As a first step towards design, we should consider whether we wish to support each of the listed NUnit extensions in TestCentric. The following is a first cut, which may be updated as we proceed.

### IDriverFactory

The existing V2 Driver must be supported. Support for other extensions, if they exist, is not necessary.

### IProjectLoader

The existing NUnit project loader must be supported. The Visual Studio project loader is extremely limited and we could replace it with a TestCentric version. Optionally, both could be internalized.

### IResultWriter

The existing V2 Result Writer should probably be supported or internalized,

### IService

Since there are no existing NUnit extensions and (to my knowledge) none under development, this does not need to be supported. The TC extension point will be retained for future development

### ITestEventListener

This needs strong support because of it's extensive use by users. In addition, we should support the existing Team City event listener.

**Comment by CharliePoole** [comment]
Blocked by TestCentric/TestCentric.Extensibility#44

**Comment by CharliePoole** [comment]
The remaining, incomplete parts of this issue have been made unnecessary because of changes in TestCentric.Extensibility, which now encapsulates the code needed to deal with NUnit extensins.
