### ISSUE TITLE
Make all agents pluggable extensions

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-engine#3]
By separating agents as individual extensions, we can simplify the engine package itself significantly. The engine package would be modified to include dependencies on those agents we want to treat as standard and additional agents could be installed by the user on demand.

### Standard Agents

The 2.0 engine will include one .NET Framework agent and either one or two .NET Core agents as dependencies. All other available agents would be user-installable. The initial 2.0.0 release will support the following default agents:

- .NET Framework 4.6.2 
- .NET 6.0 (latest LTS, replace when 8.0 is released)
- .NET 7.0 (latest agent, remove or replace as needed)

### Preliminary Refactoring

Currently, the agent depends on both the `testcentric.engine.core` and the `testcentric.agent.core` assemblies. The latter made sense in an environment where all the agents were bundled in one project under our control. However, if we switch to pluggable agents, users may want to develop agents in ways we have not yet imagined - and we may want to do the same! In that environment, providing base implementations of all agent features doesn't make sense. Therefore, the code in `testcentric.agent.core` needs to be moved. Some of it will go to `testcentric.engine.core` while other items will go into the agent itself.

- [x] TestCentric/testcentric-engine#12

### Currently supported agents to be converted to extensions:

* .NET Framework 2.0
  - [x] TestCentric/testcentric-engine#4
  - [x] testcentric/net20-pluggable-agent#5
* .NET Framework 4.6.2
  - [x] TestCentric/testcentric-engine#15
  - [x] TestCentric/testcentric-engine#111
  - [x]  TestCentric/testcentric-engine#118 
  - [x] TestCentric/testcentric-gui#979
* .NET Core 2.1
  - [x] TestCentric/testcentric-engine#16
  - [x] Create netcoreapp2.1 agent extension
* .NET Core 3.1
  - [x] TestCentric/testcentric-engine#17
  - [x] Create netcoreapp3.1 agent extension
* .NET 5.0
  - [x] TestCentric/testcentric-engine#18
  - [x] Create net5.0 agent extension
* .NET 6.0
  - [x] TestCentric/testcentric-engine#109
  - [x] TestCentric/testcentric-engine#2
  - [x] TestCentric/testcentric-engine#119
  - [x] TestCentric/testcentric-gui#978
* .NET 7.0
  - [x] TestCentric/testcentric-engine#110
  - [x] TestCentric/testcentric-engine#108
  - [x] TestCentric/testcentric-engine#120
  - [x] TestCentric/testcentric-gui#977
* .NET 8.0
  - [x] TestCentric/testcentric-engine#82
